version: '3'
services:
  python:
    build: .
    environment:
      - PORT=${PORT}
    ports:
      - "8080:${PORT}"
    volumes:
      - .:/app
    command: gunicorn --bind :$PORT --workers 1 --threads 8 app:app --reload
